export const SEND_USER_EMAIL = "SEND_USER_EMAIL";
export const ADD_SENDER_USERNAME = "ADD_SENDER_USERNAME";
export const ERROR_SENDER_FETCH = "ERROR_VALIDATE_FETCH";
export const LOADING_START_SENDER = "LOADING_START_SENDER";
export const LOADING_FINISH_SENDER = "LOADING_FINISH_SENDER";
