export const VALIDATE_USER = "VALIDATE_USER";
export const ADD_VALIDATOR_USERNAME = "ADD_VALIDATOR_USERNAME";
export const ERROR_VALIDATE_FETCH = "ERROR_VALIDATE_FETCH";
export const LOADING_START_VALIDATOR = "LOADING_START_VALIDATOR";
export const LOADING_FINISH_VALIDATOR = "LOADING_FINISH_VALIDATOR";
